apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nss-mysql-pvc
  namespace: nss-portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nss-uploads-pvc
  namespace: nss-portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
