apiVersion: v1
kind: Secret
metadata:
  name: nss-portal-secret
  namespace: nss-portal
type: Opaque
stringData:
  DB_PASSWORD: "hr_password"
  MYSQL_ROOT_PASSWORD: "hr_root_password"
  MYSQL_PASSWORD: "hr_password"
  JWT_SECRET: "dvla_nss_portal_jwt_secret_key_2026"
  ADMIN_PASSWORD: "admin123"
  WIGAL_PASSWORD: "Devapps@123"
