apiVersion: v1
kind: Secret
metadata:
  name: hr-validation-secret
  namespace: hr-validation
type: Opaque
stringData:
  NEXTAUTH_SECRET: "pvc-super-secret-jwt-key-2026-production"
  NEXTAUTH_URL: "http://10.80.54.58:8080"
