apiVersion: v1
kind: Service
metadata:
  name: hr-validation-service
  namespace: hr-validation
  labels:
    app.kubernetes.io/name: hr-validation-service
spec:
  type: NodePort
  selector:
    app: hr-validation-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080
