export const GHANA_REGIONS_AND_DISTRICTS: Record<string, string[]> = {
  'Greater Accra': [
    'Accra Metropolitan',
    'Ada East',
    'Ada West',
    'Adentan Municipal',
    'Ashaiman Municipal',
    'Ayawaso Central',
    'Ayawaso East',
    'Ayawaso North',
    'Ayawaso West Municipal (East Legon)',
    'Ablekuma Central',
    'Ablekuma North',
    'Ablekuma West',
    'Ga Central',
    'Ga East (Madina / Dome / Taifa)',
    'Ga North',
    'Ga South',
    'Ga West (Amasaman)',
    'Korle Klottey (Osu / Ridge)',
    'Krowor (Nungua)',
    'La Dade Kotopon (Cantonments / La)',
    'La Nkwantanang Madina',
    'Ledzokuku (Teshie)',
    'Ningo Prampram',
    'Okaikwei North',
    'Shai Osudoku',
    'Tema West',
    'Tema Metropolitan',
    'Weija Gbawe'
  ],
  'Ashanti': [
    'Adansi Asokwa',
    'Adansi North',
    'Adansi South',
    'Afigya Kwabre North',
    'Afigya Kwabre South',
    'Ahafo Ano North',
    'Ahafo Ano South East',
    'Ahafo Ano South West',
    'Amansie Central',
    'Amansie South',
    'Amansie West',
    'Asante Akim Central',
    'Asante Akim North',
    'Asante Akim South',
    'Asokwa Municipal',
    'Atwima Kwanwoma',
    'Atwima Mponua',
    'Atwima Nwabiagya Municipal',
    'Atwima Nwabiagya North',
    'Bekwai Municipal',
    'Bosome Freho',
    'Bosomtwe',
    'Ejisu Municipal',
    'Ejura Sekyedumase',
    'Juaben Municipal',
    'Kumasi Metropolitan (Adum / Central)',
    'Kwabre East',
    'Kwadaso Municipal',
    'Mampong Municipal',
    'Obuasi East',
    'Obuasi Municipal',
    'Oforikrom Municipal',
    'Offinso North',
    'Offinso South',
    'Old Tafo Municipal',
    'Sekyere Afram Plains',
    'Sekyere Central',
    'Sekyere East',
    'Sekyere Kumawu',
    'Sekyere South',
    'Suame Municipal'
  ],
  'Western': [
    'Ahanta West',
    'Amenfi Central',
    'Amenfi East',
    'Amenfi West',
    'Effia Kwesimintsim Municipal',
    'Ellembelle',
    'Jomoro',
    'Mpohor',
    'Nzema East',
    'Prestea-Huni Valley',
    'Sekondi-Takoradi Metropolitan',
    'Shama',
    'Tarkwa-Nsuaem Municipal',
    'Wassa East'
  ],
  'Eastern': [
    'Abuakwa North',
    'Abuakwa South (Kibi)',
    'Achease',
    'Akuapem North',
    'Akuapem South',
    'Akyemansa',
    'Asene Manso Akroso',
    'Atiwa East',
    'Atiwa West',
    'Birim Central (Akim Oda)',
    'Birim North',
    'Birim South',
    'Denkyembour',
    'Fanteakwa North',
    'Fanteakwa South',
    'Kwahu Afram Plains North',
    'Kwahu Afram Plains South',
    'Kwahu East',
    'Kwahu South',
    'Kwahu West (Nkawkaw)',
    'Lower Manya Krobo',
    'New Juaben North',
    'New Juaben South (Koforidua)',
    'Nsawam Adoagyiri',
    'Suhum Municipal',
    'Upper Manya Krobo',
    'Upper West Akim',
    'West Akim',
    'Yilo Krobo'
  ],
  'Central': [
    'Abura Asebu Kwamankese',
    'Agona East',
    'Agona West (Swedru)',
    'Ajumako Enyan Essiam',
    'Asikuma Odoben Brakwa',
    'Assin Central (Fosu)',
    'Assin North',
    'Assin South',
    'Awutu Senya East (Kasoa)',
    'Awutu Senya West',
    'Cape Coast Metropolitan',
    'Effutu (Winneba)',
    'Ekumfi',
    'Gomoa Central',
    'Gomoa East',
    'Gomoa West',
    'Komenda Edina Eguafo Abirem',
    'Mfantsiman (Saltpond)',
    'Twifo Atti Morkwa',
    'Twifo Heman Lower Denkyira',
    'Upper Denkyira East (Dunkwa-on-Offin)',
    'Upper Denkyira West'
  ],
  'Northern': [
    'Gushegu Municipal',
    'Karaga',
    'Kpandai',
    'Kumbungu',
    'Mion',
    'Nanton',
    'Nanumba North (Bimbilla)',
    'Nanumba South',
    'Sagnarigu Municipal',
    'Savelugu Municipal',
    'Tamale Metropolitan',
    'Tatale Sanguli',
    'Tolon',
    'Yendi Municipal',
    'Zabzugu'
  ],
  'Volta': [
    'Adaklu',
    'Afadjato South',
    'Agotime Ziope',
    'Akatsi North',
    'Akatsi South',
    'Anloga',
    'Central Tongu',
    'Ho Metropolitan',
    'Ho West',
    'Hohoe Municipal',
    'Keta Municipal',
    'Ketu North',
    'Ketu South (Aflao)',
    'Kpando Municipal',
    'North Dayi',
    'North Tongu',
    'South Dayi',
    'South Tongu'
  ],
  'Upper East': [
    'Bawku Municipal',
    'Bawku West',
    'Binduri',
    'Bolgatanga East',
    'Bolgatanga Municipal',
    'Bongo',
    'Builsa North',
    'Builsa South',
    'Garu',
    'Kassena Nankana Municipal (Navrongo)',
    'Kassena Nankana West',
    'Nabdam',
    'Pusiga',
    'Talensi',
    'Tempane'
  ],
  'Upper West': [
    'Daffiama Bussie Issa',
    'Jirapa Municipal',
    'Lambussie Karni',
    'Lawra Municipal',
    'Nadowli Kaleo',
    'Nandom Municipal',
    'Sissala East',
    'Sissala West',
    'Wa East',
    'Wa Municipal',
    'Wa West'
  ],
  'Bono': [
    'Banda',
    'Berekum East',
    'Berekum West',
    'Dormaa Central',
    'Dormaa East',
    'Dormaa West',
    'Jaman North',
    'Jaman South',
    'Sunyani Municipal',
    'Sunyani West',
    'Tain',
    'Wenchi Municipal'
  ],
  'Bono East': [
    'Atebubu-Amantin',
    'Kintampo North',
    'Kintampo South',
    'Nkoranza North',
    'Nkoranza South',
    'Pru East',
    'Pru West',
    'Sene East',
    'Sene West',
    'Techiman Municipal',
    'Techiman North'
  ],
  'Ahafo': [
    'Asunafo North (Goaso)',
    'Asunafo South',
    'Asutifi North',
    'Asutifi South',
    'Tano North',
    'Tano South'
  ],
  'Western North': [
    'Aowin Municipal',
    'Bia East',
    'Bia West',
    'Bibiani Anhwiaso Bekwai',
    'Bodi',
    'Juaboso',
    'Sefwi Akontombra',
    'Sefwi Wiawso Municipal',
    'Suaman'
  ],
  'Oti': [
    'Biakoye',
    'Guan',
    'Jasikan',
    'Kadjebi',
    'Krachi East (Dambai)',
    'Krachi Nchumuru',
    'Krachi West',
    'Nkwanta North',
    'Nkwanta South'
  ],
  'North East': [
    'Bunkpurugu Nakpanduri',
    'Chereponi',
    'East Mamprusi (Nalerigu)',
    'Mamprugu Moagduri',
    'West Mamprusi (Walewale)',
    'Yunyoo-Nasuan'
  ],
  'Savannah': [
    'Bole',
    'Central Gonja',
    'East Gonja (Salaga)',
    'North East Gonja',
    'North Gonja',
    'Sawla-Tuna-Kalba',
    'West Gonja (Damongo)'
  ]
};

export const GHANA_REGIONS = Object.keys(GHANA_REGIONS_AND_DISTRICTS);

export function getDistrictsForRegion(regionName?: string): string[] {
  if (!regionName) return [];
  // Find matching key case-insensitively or exactly
  const match = Object.keys(GHANA_REGIONS_AND_DISTRICTS).find(
    r => r.toLowerCase() === regionName.toLowerCase()
  );
  return match ? GHANA_REGIONS_AND_DISTRICTS[match] : [];
}
